version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - LOG_FILE_PATH=/var/log/app/application.log  # Just the base filename
      - TZ=Asia/Phnom_Penh
    volumes:
      - ./logs:/var/log/app  # Mount logs directory
    networks:
      - app-network
    #user: root  # Ensure write permission

networks:
  app-network:
    driver: bridge
